os: linux
language: c
dist: bionic
cache: ccache

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autotools-dev autoconf automake

script: ./autogen.sh && mkdir build && cd build && ../configure && make

